name: Study-docs CI

# 触发条件：在 push 到 master 分支后
on:
  push:
    branches:
      - master

# 任务
jobs:
  build:
    runs-on: ubuntu-latest # 服务器环境：最新版 Ubuntu

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      # 拉取代码
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # “最近更新时间” 等 git 日志相关信息，需要拉取全部提交记录

      - name: Setup environment Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      # 缓存 node_modules
      - name: Cache ~/.pnpm-store
        uses: actions/cache@v3
        env:
          cache-name: cache-pnpm-store
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-preview-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-preview-${{ env.cache-name }}-
            ${{ runner.os }}-preview-
            ${{ runner.os }}-

      # 如果缓存没有命中，安装依赖
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # 生成静态文件
      - name: Build
        run: pnpm build
        env:
          DOC_ENV: preview

      - name: script deploy
        env:
          ACCESS_TOKEN_DEPLOY: ${{secrets.STUDY_DOCS_TOKEN}}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./src/.vuepress/dist
        run: |
          chmod +x ./scripts/deploy.sh
          bash ./scripts/deploy.sh
